export const DEPARTMENTS = [
  { id: 1,  name: '교통행정과' },
  { id: 2,  name: '도로정책과' },
  { id: 3,  name: '건축개발과' },
  { id: 4,  name: '토지관리과' },
  { id: 5,  name: '자치행정과' },
  { id: 6,  name: '총무과' },
  { id: 7,  name: '식품의약과' },
  { id: 8,  name: '감염병관리과' },
  { id: 9,  name: '환경정책과' },
  { id: 10, name: '기후대기과' },
  { id: 11, name: '관광과' },
  { id: 12, name: '스포츠산업과' },
  { id: 13, name: '농업정책과' },
  { id: 14, name: '축산정책과' },
  { id: 15, name: '사회복지과' },
  { id: 16, name: '노인복지과' },
  { id: 17, name: '장애인복지과' },
  { id: 18, name: '세정과' },
  { id: 19, name: '수자원관리과' },
  { id: 20, name: '기반산업과' },
  { id: 21, name: '일자리경제과' },
  { id: 22, name: '투자유치과' },
  { id: 23, name: '중소벤처기업과' },
  { id: 24, name: '산단개발과' },
  { id: 25, name: '문화예술과' },
  { id: 26, name: '문화자원과' },
  { id: 27, name: '문화산업과' },
  { id: 28, name: '남도의병역사박물관 개관준비단' },
  { id: 29, name: '산림자원과' },
  { id: 30, name: '산림휴양과' },
  { id: 31, name: '여순사건지원단' },
  { id: 32, name: '기획홍보담당관' },
  { id: 33, name: '소방행정과' },
  { id: 34, name: '화재대응과' },
  { id: 35, name: '구조구급과' },
  { id: 36, name: '예방안전과' },
  { id: 37, name: '소방감사담당관' },
  { id: 38, name: '소방교육과' },
  { id: 39, name: '119종합상황실' },
];

export const getDeptName = (id) => DEPARTMENTS.find(d => d.id === id)?.name ?? '';
export const getDeptId   = (name) => DEPARTMENTS.find(d => d.name === name)?.id ?? null;
